name: tri_express
description: "Tri Express App"
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  faker: ^2.2.0
  firebase_core: ^4.1.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  fpdart: ^1.1.1
  get_it: ^8.2.0
  go_router: ^16.1.0
  image_picker: ^1.2.0
  intl: any
  mobile_scanner: ^7.0.1
  mocktail: ^1.0.4
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: HelveticaNeue
      fonts:
        # Thin
        - asset: fonts/HelveticaNeueThin.otf
          weight: 100
        - asset: fonts/HelveticaNeueThinItalic.otf
          weight: 100
          style: italic

        # UltraLight
        - asset: fonts/HelveticaNeueUltraLight.otf
          weight: 200
        - asset: fonts/HelveticaNeueUltraLightItalic.otf
          weight: 200
          style: italic

        # Light
        - asset: fonts/HelveticaNeueLight.otf
          weight: 300
        - asset: fonts/HelveticaNeueLightItalic.otf
          weight: 300
          style: italic

        # Roman (Regular)
        - asset: fonts/HelveticaNeueRoman.otf
          weight: 400
        - asset: fonts/HelveticaNeueItalic.ttf
          weight: 400
          style: italic

        # Medium
        - asset: fonts/HelveticaNeueMedium.otf
          weight: 500
        - asset: fonts/HelveticaNeueMediumItalic.otf
          weight: 500
          style: italic

        # Bold
        - asset: fonts/HelveticaNeueBold.otf
          weight: 700
        - asset: fonts/HelveticaNeueBoldItalic.otf
          weight: 700
          style: italic

        # Heavy
        - asset: fonts/HelveticaNeueHeavy.otf
          weight: 800
        - asset: fonts/HelveticaNeueHeavyItalic.otf
          weight: 800
          style: italic

        # Black
        - asset: fonts/HelveticaNeueBlack.otf
          weight: 900
        - asset: fonts/HelveticaNeueBlackItalic.otf
          weight: 900
          style: italic
