import 'package:flutter/material.dart';

const black = Color(0xFF212329);
const border = Color(0xFFEAEFF5);
const danger = Color(0xFFE71B1B);
const gray = Color(0xFFBBBBBB);
const graySecondary = Color(0xFFCCCCCC);
const grayTertiary = Color(0xFF767676);
const light = Color(0xFFFFFFFF);
const lightBlue = Color(0xFFECEFFF);
const primary = Color(0xFF0E2BCD);
const secondary = Color(0xFF25C0DE);
const success = Color(0xFF47C062);
const successEmphasis = Color(0xFFE5FFEA);
const text = Color(0xFF152B52);
const warning = Color(0xFFD7974D);
const warningEmphasis = Color(0xFFEDDC3F);
const whiteSecondary = Color(0xFFEFF1F3);
const whiteTertiary = Color(0xFFF6F6F6);
const primaryGradientEnd = Color(0xFF8692D9);